/* HISTORY OF JAVASCIPT
   

    BRANDEN EICH INVENTED A LANGUAHE CALLED  MOCHA 
     
    THEN IN NETSCAPE MOCHA USED AS NAME LIVESCRIPT
    AND AFTER THAT NAME LIVESCRIPT CHANGED AND                                      ON THE OTHER HAND 
    BECAME JAVASCREPT                                                              MICROSOFT USED LAMGUAGE CALLED J SCREPT(WICH IS MADE
    ITS USED FOR NETSCAPE BROWSER                                                  BY NETSCAPES JAVASCRIPT) FOR HIS OWN BROWSER


     IN THIS POINT OF TIME FOR DEFFERENT BROWSER THERE ARE DEFFERENT LANGUAGES. WICH IS VERY DIFFICULT

     ECMA WICH IS A STANDRIZED ORGANISATION SOLVED THIS PROBLEM
     AND STANDRIZE A SPECIFICATION FOR THESE SCRIPTING LAMGUAGE
     THATS WHY JAVASCRIPT ALSO CALLED AS ECMAscript
     A COMMITY NAME AS TC39 MONITERS THIS LANGUAGE



 
     WHAT WE BUILD WITH THE HELP OF JAVASCRIPT


    FOR FRONTEND WITH HELP OF REACT OR ANGULER   EX. FACEBOOK,NETFIX,BBC,PAYPAL
    FOR BACKEND  WITH HELP OF NODE JS AND EXPRESS
    FPR APP DEVELOPMENT WITH HELP OF REACT NATIVE   EX. INSTAGRAM,DISCORD,MYNTRA,PINTREST
    DEXTOP APP WITH HELP OF ELECTRON JS DISCORD,VS CODE
    AND MANY MORE OTHER THINGS  */ 

    





    
                                                                                    
                                                                                    
                                                                             